### ISSUE TITLE
使用5月29日固件 MT7921无法启动

### ISSUE THREAD

**Issue by aliandown** [DHDAXCW/hinlink-opc-h6xk#1]
刚刷完固件第一天没有驱动没有问题，正常使用，使用大概过了一个星期左右，这一个星期里面，设备没有设置自动重起计划，一直开机使用就出现这个问题 

[    7.102927] mt7921e 0000:01:00.0: assign IRQ: got 22
[    7.102969] mt7921e 0000:01:00.0: enabling device (0000 -> 0002)
[    7.103594] mt7921e 0000:01:00.0: enabling bus mastering
[    7.122403] mt7921e 0000:01:00.0: ASIC revision: 79610010
[    7.124394] mt7921e: probe of 0000:01:00.0 failed with error -110

**Comment by aliandown** [comment]
5月29日之前的固件也试过，也是同样的问题，刷无固件正常使用，过几天就不行了

**Comment by aliandown** [comment]
6月3日固件已刷 使用中的日志信息

[   18.769688] fast-classifier: starting up
[   19.423102] mt7921e 0000:01:00.0: Message 00020003 (seq 12) timeout
[   19.423716] phy0-ap0: failed to set key (1, ff:ff:ff:ff:ff:ff) to hardware (-110)
[   19.424634] fast-classifier: registered
[   19.511161] mt7921e 0000:01:00.0: HW/SW Version: 0x8a108a10, Build Time: 20230331110902a
[   19.511161] 
[   19.522699] mt7921e 0000:01:00.0: WM Firmware Version: ____010000, Build Time: 20230331110939
[   21.044180] IPv6: ADDRCONF(NETDEV_CHANGE): phy0-ap0: link becomes ready
[   21.044903] br-lan: port 4(phy0-ap0) entered blocking state
[   21.045415] br-lan: port 4(phy0-ap0) entered forwarding state

[    7.217877] usbserial: USB Serial support registered for generic
[    7.248444] xt_time: kernel timezone is -0000
[    7.252575] usbcore: registered new interface driver cdc_mbim
[    7.366100] mt7921e 0000:01:00.0: assign IRQ: got 22
[    7.366142] mt7921e 0000:01:00.0: enabling device (0000 -> 0002)
[    7.366729] mt7921e 0000:01:00.0: enabling bus mastering
[    7.386980] mt7921e 0000:01:00.0: ASIC revision: 79610010
[    7.468647] PPP generic driver version 2.4.2
[    7.469883] mt7921e 0000:01:00.0: HW/SW Version: 0x8a108a10, Build Time: 20230331110902a
[    7.469883] 
[    7.471332] PPP MPPE Compression module registered
[    7.473952] NET: Registered PF_PPPOX protocol family
[    7.475558] PPTP driver version 0.8.5

[   17.122208] rk_gmac-dwmac fe2a0000.eth eth0: Link is Up - 1Gbps/Full - flow control rx/tx
[   17.122978] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[   18.769688] fast-classifier: starting up
[   19.423102] mt7921e 0000:01:00.0: Message 00020003 (seq 12) timeout
[   19.423716] phy0-ap0: failed to set key (1, ff:ff:ff:ff:ff:ff) to hardware (-110)
[   19.424634] fast-classifier: registered
[   19.511161] mt7921e 0000:01:00.0: HW/SW Version: 0x8a108a10, Build Time: 20230331110902a
[   19.511161] 
[   19.522699] mt7921e 0000:01:00.0: WM Firmware Version: ____010000, Build Time: 20230331110939
[   21.044180] IPv6: ADDRCONF(NETDEV_CHANGE): phy0-ap0: link becomes ready
[   21.044903] br-lan: port 4(phy0-ap0) entered blocking state
[   21.045415] br-lan: port 4(phy0-ap0) entered forwarding state

[45257.785340] mt7921e 0000:01:00.0: Message 00020003 (seq 3) timeout
[45257.786084] phy0-ap0: failed to set key (1, ff:ff:ff:ff:ff:ff) to hardware (-110)
[45260.857138] mt7921e 0000:01:00.0: Message 00020002 (seq 4) timeout
[45263.929096] mt7921e 0000:01:00.0: Message 00020002 (seq 6) timeout
[45264.012479] mt7921e 0000:01:00.0: HW/SW Version: 0x8a108a10, Build Time: 20230331110902a
[45264.012479] 
[45264.023751] mt7921e 0000:01:00.0: WM Firmware Version: ____010000, Build Time: 20230331110939

**Comment by DHDAXCW** [comment]
我看一下

**Comment by aliandown** [comment]
查了一下其他网站 国外的大神是这样修复的，不知道能不能帮到你
https://patchwork.kernel.org/project/linux-wireless/patch/53f713fe1c543037c8b49d80dae0d1eaeb2a3457.1679123603.git.deren.wu@mediatek.com/

**Comment by DHDAXCW** [comment]
可以，我先等其他编译完刷上测试

**Comment by DHDAXCW** [comment]
已加上，这边测试网卡上下传输性能没问题。感谢反馈~我正好也在用这个网卡

**Comment by DHDAXCW** [comment]
我已把今天的固件删除了，重新固件

**Comment by aliandown** [comment]
希望这次可以把问题解决
